
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.camel.helloworld.soapService;

import java.util.HashMap;
import java.util.Map;

/**
 * This class was generated by Apache CXF 3.1.7 2018-02-02T12:34:20.850+08:00
 * Generated source version: 3.1.7
 *
 */

// @javax.jws.WebService(serviceName = "QueryServiceService", portName =
// "QueryServicePort", targetNamespace = "http://query.service.org/",
// wsdlLocation = "file:/C:/Users/CYX/Desktop/queryInfo.wsdl", endpointInterface
// = "org.service.query.QueryServiceInter")

public class QueryServicePortImpl implements QueryServiceInter {

	private Map<String, String> carMap = new HashMap<>();

	public QueryServicePortImpl() {
		init();
	}

	private void init(){
		carMap.put("1", "BenChi, price 320000!");
		carMap.put("2", "Auto, price 306000!");
		carMap.put("3", "BMW, price 339000!");
	}

	public String queryCarInfomation(String carParam) {
		System.out.println("Executing operation queryCarInfomation");
		System.out.println(carParam);
		try {
			return carMap.get(carParam);
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	public String queryPersonnelInformation(String peopleParam) {

		System.out.println("Executing operation queryPersonnelInformation");

		System.out.println(peopleParam);

		try {
			String _return = "";
			return _return + "987654321";
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
